version: "3.9"
services:
  marketing:
    build:
      context: .
      dockerfile: apps/marketing/Dockerfile
    environment:
      - NODE_ENV=production
    # marketing no longer binds host port; gateway will expose 3000
  docs:
    build:
      context: .
      dockerfile: apps/docs/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
  gateway:
    image: nginx:1.25-alpine
    depends_on:
      - marketing
      - docs
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro